# Generated by Django 3.1.4 on 2021-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[

                ('Date', models.DateTimeField(verbose_name='Flight Date')),
                ('Aéroport_départ', models.CharField(
                    max_length=200, verbose_name='Depart Airport')),
                ('depart_x', models.CharField(
                    max_length=200, verbose_name='Depart X ')),
                ('depart_y', models.CharField(
                    max_length=200, verbose_name='Depart Y ')),
                ('départ_IATA', models.CharField(
                    max_length=3, verbose_name='Depart Airport IATA')),
                ('Heurelocale', models.TimeField(verbose_name='Depart hour')),
                ('destination_IATA', models.CharField(
                    max_length=3, verbose_name='Arrival Airport IATA')),
                ('Durée_IATA', models.TimeField(verbose_name='Flight duration')),
                ('HeureArrivé', models.TimeField(verbose_name='Arrival hour')),
                ('Aéroport_Destination', models.CharField(
                    max_length=200, verbose_name='Arrival Airport ')),
                ('destination_x', models.CharField(
                    max_length=200, verbose_name='Destination X ')),
                ('destination_y', models.CharField(
                    max_length=200, verbose_name='Destination Y')),
                ('Num_Vol', models.CharField(
                    max_length=200, verbose_name='flight number ')),
                ('Prix_Camp1', models.CharField(
                    max_length=200, verbose_name='Flight Price')),
                ('Compagnie', models.CharField(
                    max_length=120, verbose_name='Flight Compagnie')),
            ],
        ),
    ]
