# Generated by Django 3.1.4 on 2021-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210910_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Date',
            field=models.CharField(max_length=10, verbose_name='Flight Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Durée_IATA',
            field=models.CharField(max_length=5, verbose_name='Flight duration'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='HeureArrivé',
            field=models.CharField(max_length=5, verbose_name='Arrival hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Heurelocale',
            field=models.CharField(max_length=5, verbose_name='Depart hour'),
        ),
    ]
