# Generated by Django 3.1.4 on 2021-09-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210910_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='Durée_IATA',
            new_name='Durée_trajet',
        ),
    ]
