# Generated by Django 3.1.4 on 2021-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210910_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Date',
            field=models.CharField(max_length=200, verbose_name='Flight Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Durée_trajet',
            field=models.CharField(max_length=200, verbose_name='Flight duration'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='HeureArrivé',
            field=models.CharField(max_length=200, verbose_name='Arrival hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Heurelocale',
            field=models.CharField(max_length=200, verbose_name='Depart hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_IATA',
            field=models.CharField(max_length=200, verbose_name='Arrival Airport IATA'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='départ_IATA',
            field=models.CharField(max_length=200, verbose_name='Depart Airport IATA'),
        ),
    ]
