# Generated by Django 3.1.4 on 2021-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210910_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Date',
            field=models.DateField(verbose_name='Flight Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Durée_trajet',
            field=models.TimeField(verbose_name='Flight duration'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='HeureArrivé',
            field=models.TimeField(verbose_name='Arrival hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Heurelocale',
            field=models.TimeField(verbose_name='Depart hour'),
        ),
    ]
