# Generated by Django 3.1.4 on 2021-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210910_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Aéroport_Destination',
            field=models.TextField(max_length=200, verbose_name='Arrival Airport '),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Aéroport_départ',
            field=models.TextField(max_length=200, verbose_name='Depart Airport'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Compagnie',
            field=models.TextField(max_length=120, verbose_name='Flight Compagnie'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Date',
            field=models.TextField(verbose_name='Flight Date'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Durée_trajet',
            field=models.TextField(verbose_name='Flight duration'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='HeureArrivé',
            field=models.TextField(verbose_name='Arrival hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Heurelocale',
            field=models.TextField(verbose_name='Depart hour'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Num_Vol',
            field=models.TextField(max_length=200, verbose_name='flight number '),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Prix_Camp1',
            field=models.TextField(max_length=200, verbose_name='Flight Price'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='depart_x',
            field=models.TextField(max_length=200, verbose_name='Depart X '),
        ),
        migrations.AlterField(
            model_name='flights',
            name='depart_y',
            field=models.TextField(max_length=200, verbose_name='Depart Y '),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_IATA',
            field=models.TextField(max_length=200, verbose_name='Arrival Airport IATA'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_x',
            field=models.TextField(max_length=200, verbose_name='Destination X '),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_y',
            field=models.TextField(max_length=200, verbose_name='Destination Y'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='départ_IATA',
            field=models.TextField(max_length=200, verbose_name='Depart Airport IATA'),
        ),
    ]
