# Generated by Django 3.1.4 on 2021-09-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210910_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flights',
        ),
    ]
