# Generated by Django 3.1.4 on 2021-09-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_flightt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Compagnie',
            field=models.CharField(max_length=200, verbose_name='Flight Compagnie'),
        ),
    ]
