# Generated by Django 3.1.4 on 2021-09-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210910_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Num_Vol',
            field=models.CharField(max_length=300, verbose_name='flight number '),
        ),
    ]
